### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by matthias-mueller**

### CODE REVIEW

**Comment by nuest** [comment]
Maybe squash the commits next time?

http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by matthias-mueller** [comment]
I edit the documentation directly in github and save them occasionally. How can I squash these edits afterwards?

**Comment by nuest** [comment]
Probably not on GitHub, you would have to to that in you local clone and then push that you your GitHub fork...

**Comment by matthias-mueller** [comment]
Yeah, but using GitHub's markdown editor is just so convenient. Apart from the longer commit logs, I do not see any particular advantages in squashing.

https://stackoverflow.com/questions/7774801/git-how-to-squash-several-commits-that-have-been-pushed-to-a-remote-repo

"First of all, avoid squashing and in general rewriting history unless you absolutely have to. Having trivial commits is not reason to squash pushed commits. If they can stay, let them stay."

**Comment by autermann** [comment]
> Yeah, but using GitHub's markdown editor is just so convenient. Apart from the shorter commit logs, I do not see any particular advantages in squashing.
> 
> https://stackoverflow.com/questions/7774801/git-how-to-squash-several-commits-that-have-been-pushed-to-a-remote-repo
>
> > First of all, avoid squashing and in general rewriting history unless you absolutely have to. Having trivial commits is not reason to squash pushed commits. If they can stay, let them stay.

If you edit a file, you can tell GitHub to do that in a specific branch. After that you can continue editing in that branch and before you create a pull request you checkout the branch locally and squash the commits (btw: there are some really good Markdown editors out there, e.g. [Atom](https://atom.io/) with [markdown-preview](https://atom.io/packages/markdown-preview)).

Of course there is nothing bad about small commits, but having several commits with the very same non-descriptive commit message is kind of useless. IMHO the quote applies to repositories/branches that are used by several people (e.g. you would never rewrite something in `52North/WPS#develop`, but it's totally fine if you do it in your own fork in a branch just for this purpose...

**Pull request merged**
